"""PlatformIO pre-build script: turn ../credentials.ini into src/secrets.h.

The router admin password stays in one place (the repo's gitignored
credentials.ini, also used by the Python client). Wifi credentials live in
its [wifi] section. Also embeds a SHA-512-crypt test vector computed by the
Python client, so the firmware can check its own implementation at boot.
"""
import configparser
import subprocess
from pathlib import Path

Import("env")  # noqa: F821 - provided by PlatformIO

project = Path(env.subst("$PROJECT_DIR"))  # noqa: F821
repo = project.parent
ini_path = repo / "credentials.ini"
out_path = project / "src" / "secrets.h"

ini = configparser.ConfigParser()
ini.read(ini_path)
missing = [f"[{s}] {k}" for s, keys in {"router": ["password"], "wifi": ["ssid", "password"]}.items()
           for k in keys if not ini.get(s, k, fallback="")]
if missing:
    raise SystemExit(f"{ini_path}: missing {', '.join(missing)}")


def c_str(value: str) -> str:
    # octal escapes for anything unusual: always exactly 3 digits, so never ambiguous
    out = "".join(c if (c.isascii() and c.isprintable() and c not in '\\"?') else "".join(f"\\{b:03o}" for b in c.encode()) for c in value)
    return f'"{out}"'


TEST_PASSWORD, TEST_SALT = "Test-Wachtwoord!", "AbCdEfGh12345678"
expected = subprocess.run(
    ["python3", "-c", f"import sagemcom5598 as s; print(s._sha512_crypt({TEST_PASSWORD!r}.encode(), {TEST_SALT!r}))"],
    cwd=repo, check=True, capture_output=True, text=True,
).stdout.strip()

values = {
    "WIFI_SSID": ini.get("wifi", "ssid"),
    "WIFI_PASSWORD": ini.get("wifi", "password"),
    "ROUTER_IP": ini.get("router", "ip", fallback="192.168.1.254"),
    "ROUTER_LOGIN": ini.get("router", "login", fallback="beheer"),
    "ROUTER_PASSWORD": ini.get("router", "password"),
    "CRYPT_TEST_PASSWORD": TEST_PASSWORD,
    "CRYPT_TEST_SALT": TEST_SALT,
    "CRYPT_TEST_EXPECTED": expected,
}
text = "// Generated by gen_secrets.py from ../credentials.ini - do not edit, do not commit.\n#pragma once\n"
text += "".join(f"#define {k} {c_str(v)}\n" for k, v in values.items())
if not out_path.exists() or out_path.read_text() != text:
    out_path.write_text(text)
    print(f"gen_secrets: wrote {out_path.name}")
